spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-kafka-protobuf-demo-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.sanshengshui.kafka.kafka.CallbackDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.sanshengshui.kafka.kafka.CallbackSerializer